This notebook evaluates the collision dynamics of tRNAs and ribosomes in a polydisperse setting at biologically-accurate crowding levels at 1) different time scales and 2) total simulation volume

In [30]:
from src import analysis_utils as utils
import matplotlib.pyplot as plt
import numpy as np
import pickle as pkl
import seaborn as sns; sns.set()
import pandas as pd
%matplotlib inline 
%load_ext autoreload
%autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
with open("expt5_analysis.p", 'rb') as f:
    data=pkl.load(f)
tRNACollisionCount_rt = data[0]
incorrectCollisions_rt = data[1]

In [17]:
df= utils.readSimData("data/expt5_47tRNAEfTu_1ribosome_0tRNASynth_0aa_1000nmSidelength_20180424.xls")
tRNACollisionCount_rt=utils.countRibosomeCollisions(df, np.arange(1,4),np.arange(48,55))
incorrectCollisions_rt=utils.countIncorrectRibosomeCollisions(df, np.arange(1,4),np.arange(48,55))



[[ 5273.  5354.  5221.]
 [ 5049.  5172.  5093.]
 [ 4424.  4846.  4834.]
 [ 4985.  5051.  4581.]
 [ 4862.  5096.  4880.]
 [ 4502.  4951.  4845.]
 [ 5213.  5335.  5218.]]
Initial tRNA x ribosome x collisionGapNumber has shape: (7, 3, 0)
Currently processing ribosome # 0
Currently processing ribosome # 1
Currently processing ribosome # 2
Currently processing ribosome # 3
Currently processing ribosome # 4
Currently processing ribosome # 5
Currently processing ribosome # 6


In [ ]:
timesplitdf=utils.timeSplitter(df)

row_max=3
col_max=3
fig, ax = plt.subplots(row_max,col_max)

for j in range(row_max):
    for k in range(col_max):
        tRNACollisionCount_rt = utils.countRibosomeCollisions(pd.concat(timesplitdf[0:col_max*j+k+1]), np.arange(1,4),np.arange(48,55))
        #Could make 5x more efficient by summing the 2D array outputs instead of concat the original dfs.But couldn't do this for distribution
        #analysis where things are lists instead of nice clean 2D vectors.[though Could iterate through both lists, adding as we go to make new list]
        for i in range(3):
            ax[j,k].bar(.1*i+np.arange(0,7),tRNACollisionCount_rt[:,i], width=0.1, label="tRNA "+str(i))
        ax[j,k].set_title("Split "+str(col_max*j+k))

plt.tight_layout(pad=0.1, w_pad=2, h_pad=1)

#ax[j,k].set_title("# times ribosome sampled by a given tRNA")
#ax[j,k].set_xlabel("Ribosome ID #")
#ax[j,k].set_xticklabels(["0","r0","r1","r2","r3","r4","r5","r6"])
#ax[j,k].set_ylabel("# collision events")

##not summed up. As a secondary graph, maybe I can show 2 line on line graph over more fine grained accumulation of hits for a single/2 ribosomes.
#To show 1 high 1 low and then over time they become more even or something. Can get this probably from just plotting a sorted df, df sort by
#ribosome&tRNA and then plotting all tRNA hit time points.

[[ 453.  680.  565.]
 [ 471.  436.  477.]
 [ 484.  611.  708.]
 [ 531.  610.  405.]
 [ 511.  394.  340.]
 [ 509.  495.  525.]
 [ 396.  447.  440.]]
[[ 1139.  1239.  1076.]
 [  919.  1037.  1036.]
 [  832.  1060.  1153.]
 [ 1105.  1155.   963.]
 [  991.   963.   883.]
 [  793.   864.   887.]
 [  843.  1051.  1102.]]
[[ 1635.  1806.  1616.]
 [ 1497.  1484.  1598.]
 [ 1263.  1481.  1547.]
 [ 1547.  1686.  1555.]
 [ 1587.  1690.  1495.]
 [ 1124.  1288.  1373.]
 [ 1376.  1689.  1666.]]
[[ 2191.  2341.  2160.]
 [ 1923.  1961.  1973.]
 [ 1625.  1952.  2080.]
 [ 1925.  2143.  1897.]
 [ 2109.  2202.  2008.]
 [ 1643.  1711.  1734.]
 [ 1969.  2280.  2345.]]
[[ 2797.  2841.  2733.]
 [ 2382.  2427.  2485.]
 [ 2166.  2610.  2672.]
 [ 2303.  2694.  2330.]
 [ 2597.  2761.  2577.]
 [ 2073.  2285.  2247.]
 [ 2507.  2843.  2901.]]
[[ 3427.  3440.  3265.]
 [ 2904.  2884.  3063.]
 [ 2645.  3053.  2967.]
 [ 2756.  3072.  2777.]
 [ 2968.  3245.  3060.]
 [ 2658.  2945.  2713.]
 [ 3187.  3334.  3390.]]
[[ 3953

In [ ]:
tRNACollisionCount_rt = utils.countRibosomeCollisions(timesplitdf[k_max*j+k], np.arange(1,3),np.arange(51,55))

Citations:
1. Check model excel sheet for numbers.
2. Show citation for crowding percentage being biologically accurate/what's in a cell